name: Build
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        type: [Debug, RelWithDebInfo]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Configure
        run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DUSE_ASAN=1
      - name: Build
        run: cmake --build . --config ${{ matrix.type }}
      - name: Test
        run: ctest -C ${{ matrix.type }} --output-on-failure
